name: Build

on:
  pull_request:
  push:
  workflow_dispatch:

permissions: read-all

jobs:
  go:
    name: Go
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.1
          cache: false

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          install-only: true

      - name: Build
        run: make build
