name: Build

on:
  pull_request:
  push:
    branches:
      - '*'
  workflow_dispatch:

permissions: read-all

jobs:
  app:
    name: App
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.1
          cache: false

      - name: Set up Cosign
        uses: sigstore/cosign-installer@v3.1.2

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          install-only: true

      - name: Build
        run: make build
